syntax = "proto3";

package consensus;

service ConsensusTransport {
  rpc Accept(AcceptRequest) returns (AcceptResponse) {}
  rpc Apply(ApplyRequest) returns (ApplyResponse) {}
  rpc Commit(CommitRequest) returns (CommitResponse) {}
  rpc PreAccept(PreAcceptRequest) returns (PreAcceptResponse) {}
  rpc Recover(RecoverRequest) returns (RecoverResponse) {}
}

message CommandId {
  string origin_node_id = 1;
  uint64 sequence = 2;
}

message DependencySet {
  repeated CommandId commands = 1;
}

message AcceptRequest {
  CommandId command_id = 1;
  Ballot ballot = 2;
  EventPayload event = 3;
  LogicalTimestamp timestamp_zero = 4;
  LogicalTimestamp timestamp = 5;
  DependencySet dependencies = 6;
  LastApplied last_applied = 7;
}

message AcceptResponse {
  DependencySet dependencies = 1;
  bool nack = 2;
}

message ApplyRequest {
  CommandId command_id = 1;
  EventPayload event = 2;
  LogicalTimestamp timestamp_zero = 3;
  LogicalTimestamp timestamp = 4;
  DependencySet dependencies = 5;
  ApplyHashes hashes = 6;
}

message ApplyResponse {
  bytes result = 1;
}

message ApplyHashes {
  bytes transaction_hash = 1;
  bytes execution_hash = 2;
}

message Ballot {
  uint64 round = 1;
  string node_id = 2;
}

message CommitRequest {
  CommandId command_id = 1;
  EventPayload event = 2;
  LogicalTimestamp timestamp_zero = 3;
  LogicalTimestamp timestamp = 4;
  DependencySet dependencies = 5;
}

message CommitResponse {
  bytes result = 1;
}

message EventPayload {
  bytes command = 1;
}

message LastApplied {
  repeated CommandId commands = 1;
}

message LogicalTimestamp {
  uint64 epoch = 1;
  uint64 counter = 2;
  string node_id = 3;
}

message PreAcceptRequest {
  CommandId command_id = 1;
  EventPayload event = 2;
  LogicalTimestamp timestamp_zero = 3;
  LastApplied last_applied = 4;
}

message PreAcceptResponse {
  LogicalTimestamp timestamp = 1;
  DependencySet dependencies = 2;
  bool nack = 3;
}

message RecoverRequest {
  CommandId command_id = 1;
  Ballot ballot = 2;
  EventPayload event = 3;
  LogicalTimestamp timestamp_zero = 4;
}

enum State {
  STATE_UNDEFINED = 0;
  STATE_PRE_ACCEPTED = 1;
  STATE_ACCEPTED = 2;
  STATE_COMMITTED = 3;
  STATE_APPLIED = 4;
}

message RecoverResponse {
  State local_state = 1;
  repeated CommandId wait_for = 2;
  bool superseding = 3;
  DependencySet dependencies = 4;
  LogicalTimestamp timestamp = 5;
  Ballot nack = 6;
}
