[workspace]
resolver = "2"

members = [
    "src/api/core",
    "src/api/s3", "src/api/types",
    "src/blob-store/core",
    "src/blob-store/fs",
    "src/blob-store/types",
    "src/consensus/accord",
    "src/consensus/core",
    "src/consensus/types",
    "src/core",
    "src/meta-store/core",
    "src/meta-store/inmem",
    "src/meta-store/sqlite",
    "src/meta-store/types",
    "src/so3",
]

default-members = ["src/so3"]

[workspace.package]
version = "0.1.0"
authors = ["Bromles <bromles@yandex.ru>"]
edition = "2024"
license = "MIT OR Apache-2.0"
publish = false

[profile.release]
lto = true
codegen-units = 1
opt-level = "s"
strip = true

[workspace.dependencies]
so3-core = { path = "src/core" }
so3-api-types = { path = "src/api/types" }
so3-api-core = { path = "src/api/core" }
so3-api-s3 = { path = "src/api/s3" }
so3-blob-store-types = { path = "src/blob-store/types" }
so3-blob-store-core = { path = "src/blob-store/core" }
so3-blob-store-fs = { path = "src/blob-store/fs" }
so3-consensus-types = { path = "src/consensus/types" }
so3-consensus-core = { path = "src/consensus/core" }
so3-consensus-accord = { path = "src/consensus/accord" }
so3-meta-store-types = { path = "src/meta-store/types" }
so3-meta-store-core = { path = "src/meta-store/core" }
so3-meta-store-inmem = { path = "src/meta-store/inmem" }
so3-meta-store-sqlite = { path = "src/meta-store/sqlite" }

# compression
zstd = { version = "0.13", default-features = false }
async-compression = { version = "0.4", features = ["tokio", "zstd"] }

# encoding
md-5 = { version = "0.10" }
sha2 = { version = "0.10" }
hmac = { version = "0.12" }
const-hex = { version = "1.14" }
crc32c = { version = "0.6" }
crc32fast = { version = "1.4" }

# async runtime
tokio = { version = "1.45", default-features = false, features = [
    "net",
    "rt",
    "rt-multi-thread",
    "io-util",
    "time",
    "macros",
    "sync",
    "signal",
    "fs",
    "parking_lot",
] }

# serialization/deserialization
serde = { version = "1.0", features = ["derive", 'rc'] }
serde_bytes = "0.11"
serde_json = "1.0"
quick-xml = { version = "0.37", features = ["async-tokio", "serialize"] }
toml = { version = "0.8", default-features = false, features = ["parse"] }

# logging and tracing
tracing = "0.1"
tracing-subscriber = "0.3"

# db
heed = "0.22"
rusqlite = { version = "0.36", features = ["bundled"] }
deadpool = { version = "0.12", features = ["rt_tokio_1"] }

# http
http = "1.3"
hyper = { version = "1.6", default-features = false }
hyper-util = { version = "0.1", features = ["full"] }

# tmp for PoC
axum = { version = "0.8" }
axum-extra = { version = "0.10", features = [
    "multipart",
    "typed-routing",
    "typed-header",
] }
reqwest = { version = "0.12", features = ["rustls-tls"] }

# cli
clap = { version = "4.5", features = ["derive", "env"] }

# utils
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1.17", features = ["serde"] }
bitflags = "2.9"
async-trait = "0.1"
thiserror = "2.0"
anyhow = "1.0"
mime = "0.3"
tempfile = "3.20"
url = "2.5"
bytes = "1.10"
