[graph]

[advisories]
version = 2
ignore = []

[licenses]
version = 2
allow = [
    "Apache-2.0",
    "MIT",
    "Unicode-3.0"
]

exceptions = []

[bans]
multiple-versions = "allow"
wildcards = "deny"
allow-wildcard-paths = true
deny = [
    { name = "ahash", deny-multiple-versions = true },
    { crate = "openssl", use-instead = "rustls" },
    { crate = "openssl-sys", use-instead = "rustls" },
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []
