[package]
name = "so3-maelstrom"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
so3-core.workspace = true
serde = { workspace = true, features = ["derive", "std"] }
serde_json = { workspace = true, features = ["std"] }
bytes = { workspace = true }
prost = { workspace = true }
tokio = { workspace = true, features = ["io-std", "io-util", "macros", "rt-multi-thread"] }
tokio-stream = { workspace = true }
async-trait = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["fmt", "std"] }
tempfile = { workspace = true }
uuid = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
