flowchart TB
    S3["S3-подобный HTTP API"]
    RPC["Приватный gRPC API"]
    OUC["Обработчик объектных операций"]
    IUC["Обработчик входящего консенсуса"]
    BUC["Обработчик операций над содержимым объектов"]
    COORD["Accord-координатор"]
    WB["Кэш операций"]
    AE["Движок консенсуса + \nбуфер переупорядочивания"]
    CLIENTS["gRPC-клиенты соседних узлов"]
    META["SQLite: метаданные"]
    JOURNAL["SQLite: журнал согласования"]
    BLOB["Файловая система"]

    S3 --> OUC
    RPC --> IUC
    RPC --> BUC
    OUC --> COORD
    OUC --> BLOB
    IUC --> COORD
    COORD --> WB
    COORD --> AE
    AE --> META
    COORD --> JOURNAL
    AE --> JOURNAL
    BUC --> BLOB
    OUC --> CLIENTS
    COORD --> CLIENTS