[package]
name = "so3-core"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
so3-api-core.workspace = true
so3-meta-store-core.workspace = true
so3-consensus-core.workspace = true
so3-blob-store-core.workspace = true

async-trait.workspace = true
bytes = { workspace = true }
