[package]
name = "so3-core"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
tokio = { workspace = true, features = ["fs", "io-util", "macros", "net", "rt", "sync", "time"] }
tokio-util = { workspace = true, features = ["io"] }
tokio-stream = { workspace = true, features = ["net"] }
axum = { workspace = true, features = ["macros"] }
tower-http = { workspace = true, features = ["trace", "timeout"] }
bytes = { workspace = true }
httpdate = { workspace = true }
serde = { workspace = true, features = ["derive", "std"] }
tonic = { workspace = true, features = ["codegen", "router", "transport"] }
tonic-prost = { workspace = true }
prost = { workspace = true, features = ["derive", "std"] }
tracing = { workspace = true }
async-trait = { workspace = true }
thiserror = { workspace = true }
uuid = { workspace = true, features = ["v4", "serde"] }
postcard = { workspace = true, features = ["alloc"] }
sqlx = { workspace = true, features = ["runtime-tokio", "sqlite"] }
futures-core = { workspace = true }
sha2 = { workspace = true }
const-hex = { workspace = true, features = ["alloc"] }
tempfile = { workspace = true }
dashmap = { workspace = true }

[build-dependencies]
tonic-prost-build = { workspace = true }
