[package]
name = "so3"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
so3-core = { workspace = true }

md-5 = { workspace = true }
sha2 = { workspace = true }
hmac = { workspace = true }
const-hex = { workspace = true }
crc32c = { workspace = true }
crc32fast = { workspace = true }

tokio = { workspace = true, features = ["rt-multi-thread", "net", "sync", "macros"] }
tokio-util = { workspace = true }

clap = { workspace = true, features = ["std", "derive"] }

serde = { workspace = true }
serde_bytes = { workspace = true }
serde_json = { workspace = true }
quick-xml = { workspace = true, features = ["serialize", "async-tokio"] }
toml = { workspace = true }

tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter", "fmt"] }

heed = { workspace = true }
rusqlite = { workspace = true }
deadpool = { workspace = true }

http = { workspace = true }

axum = { workspace = true }
axum-extra = { workspace = true, features = ["typed-header"] }
reqwest = { workspace = true }

chrono = { workspace = true, features = ["serde", "std", "clock"] }
uuid = { workspace = true }
async-trait = { workspace = true }
thiserror = { workspace = true }
mime = { workspace = true }
tempfile = { workspace = true }
url = { workspace = true }
